'use client';

import { useState } from 'react';
import { Star, X } from 'lucide-react';
import type { BookingPhotoRecord } from '@/types';
import { createReview } from '@/lib/services/reviewService';

const LABELS=['','Không hài lòng','Chưa tốt','Ổn','Rất tốt','Tuyệt vời'];
export default function ReviewForm({booking,userId,onClose,onSuccess}:{booking:BookingPhotoRecord;userId?:string;onClose:()=>void;onSuccess:()=>void}) {
  const [rating,setRating]=useState(0),[hover,setHover]=useState(0),[comment,setComment]=useState(''),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState('');
  const submit=async()=>{if(submitting)return;setSubmitting(true);setMessage('');const result=await createReview({bookingId:booking.id,userId,customerName:booking.customer_name,serviceTitle:booking.service_title,rating,comment});setSubmitting(false);if(result.success){setMessage('Cảm ơn bạn đã chia sẻ trải nghiệm! Đánh giá đã hiển thị trên trang chủ. 💙');window.setTimeout(onSuccess,900);}else setMessage(result.message||'Không thể gửi đánh giá.');};
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-md"><div className="auth-dialog w-full max-w-lg rounded-3xl border border-sky-200 bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><span className="section-kicker">Buổi chụp đã hoàn thành</span><h2 className="mt-2 text-xl font-black text-slate-900">Đánh Giá Trải Nghiệm Chụp</h2><p className="mt-1 text-xs text-slate-500">{booking.service_title}</p></div><button onClick={onClose} className="h-9 w-9 rounded-xl bg-slate-100 p-2"><X/></button></div><fieldset className="mt-7"><legend className="text-sm font-bold text-slate-800">Đánh giá của bạn</legend><div className="mt-3 flex gap-2" onMouseLeave={()=>setHover(0)}>{[1,2,3,4,5].map((star)=><button key={star} type="button" onMouseEnter={()=>setHover(star)} onClick={()=>setRating(star)} aria-label={`${star} sao`} className="rounded-lg p-1 focus:outline-none focus:ring-2 focus:ring-sky-500"><Star className={`h-8 w-8 ${star<=(hover||rating)?'fill-amber-400 text-amber-400':'text-slate-300'}`}/></button>)}</div><p className="mt-2 min-h-5 text-xs font-semibold text-sky-700">{LABELS[hover||rating]}</p></fieldset><label className="mt-5 block text-sm font-bold text-slate-800">Bạn cảm thấy buổi chụp thế nào?<textarea value={comment} maxLength={800} onChange={(e)=>setComment(e.target.value)} placeholder="Chia sẻ trải nghiệm của bạn..." className="booking-input mt-2 min-h-32 resize-none font-normal"/><span className="mt-1 block text-right text-[10px] font-normal text-slate-400">{comment.length}/800</span></label><p className="mt-4 text-xs text-slate-600">Đánh giá sẽ được đăng công khai ngay trên trang chủ sau khi gửi.</p>{message&&<p className={`mt-4 text-sm font-semibold ${message.startsWith('Cảm ơn')?'text-emerald-600':'text-rose-600'}`}>{message}</p>}<button onClick={submit} disabled={submitting} className="sky-button mt-6 w-full rounded-xl py-3 disabled:opacity-60">{submitting?'Đang gửi...':'Gửi Đánh Giá'}</button></div></div>;
}

